### ISSUE TITLE
Implement Meridian

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark#11]
ETA: 2023-11-08

```[tasklist]
### Tasks
- [x] Submit logs to service
- [ ] Start request attestation
- [ ] Forward headers in Lassie
- [ ] Attach attestation token 
```

**Comment by bajtos** [comment]
@juliangruber is this task/milestone still relevant?

I think the task list in the issue description is no longer accurate.
<img width="818" alt="Screenshot 2023-10-12 at 11 35 31" src="https://github.com/filecoin-station/spark/assets/1140553/5d35ba28-5fab-4934-8212-3038ab4c58aa">

As I see it, we have two work streams:
1. Implement smart contracts
2. Integrate SPARK with the smart contracts via spark-publish & spark-evaluate

The second item is covered by https://github.com/filecoin-station/spark/issues/18.

Do you have a milestone for the first one? If not, then maybe we can keep using this issue for that purpose, but need to update the task list.

Regarding the current task list - I think all three items are covered by the following issues:
- https://github.com/filecoin-station/spark/issues/25 
- https://github.com/filecoin-station/roadmap/issues/22

**Comment by juliangruber** [comment]
Yeah let's close this one, it's too generic and covers too many tasks - especially since the tasks are already captured individually
