### ISSUE TITLE
SPARK rounds & tasking

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark#13]
ETA: 2023-09-30

In order to verify that checker nodes retrieved all data, we need several checkers to redundantly perform the same retrieval so that we can use the “honest majority” approach to determine what are the expected values, like the Blake3 hash of the CAR file retrieved.

To enable the formation of majorities, we need a concept of a time-limited period - a round - during which we collect redundant measurements and then compare the results after the round is over. So, the first logical step is to introduce the concept of a SPARK round.

SPARK rounds will be aligned with MERidian rounds. MERidian rounds have a variable length based on the rate of new FIL blocks being mined. 

More details: https://www.notion.so/pl-strflt/SPARK-roadmap-to-LabWeek-23-5d41e603859a4e32908d3c818e3d4542 
```[tasklist]
### Tasks
- [x] Introduce the concept of SPARK rounds based on MERidian rounds to the Orchestrator
- [x] Introduce a new Orchestrator API that returns the current SPARK round number and the list of tasks selected for that round.
- [x] Rework Orchestrator data model to allow multiple SPARK checkers to report retrieval result for the same task
- [x] Rework the way the SPARK module schedules jobs. It should get the list of tasks at the beginning of each epoch, randomly sort them, and then perform the first TN tasks sequentially.
- [x] Add the first fraud-detection step to the SPARK/MERidian evaluation service to check whether a measurement is for a valid job
- [x] Create Grafana charts to observe the behaviour of fraud-detection algorithm
```

**Comment by bajtos** [comment]
Closing as done.

Follow-up issue to investigate glitches in IE→SPARK round mapping:
- https://github.com/filecoin-station/spark/issues/35
