### ISSUE TITLE
Robust fraud detection

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark#22]
ETA: 2024-03-31

Details to be defined later.
```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-station/spark-evaluate/issues/78
- [ ] https://github.com/filecoin-station/spark/issues/43
- [ ] https://github.com/filecoin-station/roadmap/issues/49
```
