### ISSUE TITLE
Limit rewards per IPv4 /24 subnet

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark#29]
When calculating SPARK rewards, we can see many nodes completing the same task. To make sybil attacks more expensive, we should reward only one checker in each IPv4 /24 subnet.  
```[tasklist]
### Tasks
- [x] Record "inet_group" in measurements
- [x] Evaluate inet_group field - reward one participant per group
- [x] Visualise measurements & evaluations in Grafana
```

**Comment by bajtos** [comment]
The grouping algorithm must allow us to identify participants from U.S- or E.U.- sanctioned countries to implement geofencing and ensure we don't pay them.

**Comment by patrickwoodhead** [comment]
Cloudflare using IPV6 which is slowing things down a bit.

**Comment by bajtos** [comment]
> The grouping algorithm must allow us to identify participants from U.S- or E.U.- sanctioned countries to implement geofencing and ensure we don't pay them.

We decided to implement a different solution: we put Cloudflare's WAF (web application firewall) in front of SPARK API and configured it to reject requests coming from the sanctioned countries.

**Comment by bajtos** [comment]
Visualisations:

- Winning rate: https://protocollabs.grafana.net/d/c4bd3c80-9360-4ea3-8b75-c5ecea90765b/spark?orgId=1&from=now-6h&to=now&viewPanel=30
- Fraud detection breakdown - no changes were necessary: https://protocollabs.grafana.net/d/c4bd3c80-9360-4ea3-8b75-c5ecea90765b/spark?orgId=1&from=now-6h&to=now&viewPanel=24
