### ISSUE TITLE
Deterministic task<->node assignment

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark#38]
ETA: 2024-07-31

At the moment, SPARK nodes pick tasks from the list of per-round tasks at random and the evaluation service rewards all measurements completed.

Let's rework this part to follow what we designed in [SPARK Tasking v2](https://pl-strflt.notion.site/SPARK-tasking-v2-604e26d57f6b4892946525bcb3a77104?pvs=4).

At a high level:

- Within each subnet and for each job, assign the reward to the node inside that subnet that is “closest” to the job, using the XOR distance between the node’s public key and the hash of the job definition. (See below for details.)
- The checker node should ask the tasker for the DRAND randomness,  committee index and the list of tasks for the current SPARK round. Then, it should pick `TN` closes tasks from the list, using XOR against the checker's public key as the distance metric. (See the Notion doc for more details.)
- The evaluation service should repeat the same process to decide which measurements will be further used for verifications of proofs and eligible for rewards.

Prerequisites:
- https://github.com/filecoin-station/spark/issues/27

**Tasks**

- [ ] Implement the new tasking algorithm in the Spark checker.
- [ ] Wait until the network picks up the change.
- [ ] Observe the new committee sizes and compare the real data against my modelling exercise. Check that all works as expected.
- [ ] Rework the evaluation service to apply the new tasking algorithm when evaluating the measurements

**Comment by bajtos** [comment]
Design proposal:
https://www.notion.so/spacemeridian/Spark-Tasking-v3-745b0e1020bb4000ac77acafee09e683
